import { Inter } from "next/font/google";

import "./globals.css";
import Nav from "@/components/nav/Nav.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Privacy Shield VPN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " min-h-screen px-4 py-2 lg:px-48 lg:py-10 flex-col space-y-16"
        }
      >
        <header>
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
