import { Inter } from "next/font/google";

import "./globals.css";
import Nav from "@/components/nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Privacy Shield VPN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " min-h-screen mx-4 my-2 lg:mx-48 lg:my-10 flex-col space-y-16"
        }
      >
        <header>
          <Nav />
        </header>
        {children}
      </body>
    </html>
  );
}
